##### Komang Gede Narariya Suputra/16/TI-3B
# Medical Insurance Costs

#### Pada kasus ini, terdapat data tentang informasi kesehatan dan biaya yang harus dikeluarkan oleh asuransi kesehatan. Infomasi terkait dengan data medical insurance cost adalah sebagai berikut,

1. Age: Usia penerima manfaat
2. Sex: Gender penerima manfaat (male, femele)
3. Bmi : Body Mass Index
4. Children: Jumlah anak/tanggungan yang dicover oleh pihak asuransi
5. Smoker: Status perokok (yes, no)
6. Region: Wilayah tempat tinggal penerima manfaat
7. Charges: Biaya yang dikeluarkan oleh asuransi

#### Tantangan
#### Buatlah model regresi untuk memprediksi biaya yang harus dikeluarkan oleh pihak asuransi berdasarkan data. Validasi performa model regresi Anda dengan nilai R-squared ()

#### Tasks
1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)
2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai Variance Inflation Factor (VIF) untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.
5. Evaluasi model yang Anda buat dengan nilai 
6. Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus  medical insurance costs? 

#### (Hints) Interpretasi Nilai VIF
- 1 - variabel indenpenden tidak memiliki korelasi dengan variabel independen yang lain
- 1 < VIF < 5 - variabel independen sedikit memiliki korelasi dengan variabel independen yang lain
- VIF > 5 - variabel independen memiliki korelasi yang kuat dengan variabel independen lainnya
- VIF > 10 - variabel independen miliki korelasi yang sangat kuat dengan variabel independen dan perlu diperhatikan lebi lanjut

#### (Hints) Implementasi Perhitungan VIF 
- VIF dapat dihitung secara langsung dengan menggunakan library dari statsmodels

In [8]:
import pandas as pd
import numpy as np

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [10]:
#perintah untuk membaca file csv
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [11]:
label_sex = {
    'male': 1,
    'female': 0
}

label_smoker ={
    'yes' : 1,
    'no' : 0
}

label_region ={
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
}

#code untuk tabel sex, smoker, region
df['sex'] = df['sex'].map(label_sex)
df['smoker'] = df['smoker'].map(label_smoker)
df['region'] = df['region'].map(label_region)

#untuk menampilkan csv
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [12]:
#HINTS
from statsmodels.stats.outliers_influence import variance_inflation_factor

#untuk dataset
X = df[['age', 'bmi', 'region','sex', 'smoker', 'children']]
  
#untuk vif data frame
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
  
#untuk menghitung data vif
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(vif_data)

    feature       VIF
0       age  7.588734
1       bmi  9.938670
2    region  2.789478
3       sex  2.002652
4    smoker  1.261195
5  children  1.799980

In [13]:
#mengeset dataset setelah dimodif
databaru = df
databaru.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [14]:
X = databaru.iloc[:, :-1].values
y = databaru.iloc[:, 4].values

In [15]:
Xm_train, Xm_test, ym_train, ym_test = train_test_split(X, y, test_size=0.2, random_state=100)

y = y.reshape(len(y), 1)
y.shape

(1338, 1)

In [16]:
mlr = LinearRegression()
mlr.fit(Xm_train, ym_train)

ym_pred = mlr.predict(Xm_test)

gbg = np.concatenate((ym_test, ym_pred))
gbg

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -1.74316299e-16,  1.53352525e-16,  2.68676248e-16,  1.39017721e-16,
        1.00000000e+00,  1.00000000e+00, -3.13300884e-16, -3.73323597e-16,
        1.00000000e+00, -1.00056680e-16, -2.44306080e-16,  1.16675727e-16,
       -3.37365231e-16, -3.17984922e-16, -2.05791719e-16,  1.00000000e+00,
        1.37612382e-16,  8.97714625e-17, -2.04970214e-16, -2.18438616e-16,
       -2.37048608e-16, -1.79980669e-16, -1.29073912e-16,  1.00000000e+00,
        2.37066992e-16,  1.00000000e+00, -3.09670514e-16,  1.00000000e+00,
        1.00000000e+00,  1.35081677e-16,  4.69422252e-17,  6.58777809e-17,
        1.00000000e+00,  1.00000000e+00, -2.29688779e-16, -1.52648661e-16,
       -2.58868978e-16,  1.00000000e+00, -3.27034598e-16,  1.00000000e+00,
        1.73448942e-16,  6.34416325e-17, -2.44219984e-16,  1.00600670e-16,
        5.95108480e-17,  1.34267565e-16,  1.32108332e-16, -1.32731726e-16,
       -3.45256517e-16,  1.56382694e-16, -2.31755711e-16,  1.91651523e-16,
       -4.36294308e-16, -3.73296687e-16,  1.72641798e-16,  1.90434871e-16,
       -1.95797721e-16,  1.00000000e+00,  9.03065792e-17, -2.46207948e-16,
        2.27483355e-16,  6.86191417e-17, -1.61144257e-16,  1.37602215e-16,
       -3.15262953e-16,  2.70132527e-16,  6.16532315e-17,  1.89332432e-16,
       -2.69099012e-16,  1.00000000e+00,  1.73238180e-16,  3.04232682e-17,
       -1.98041948e-16,  1.00000000e+00,  5.01372989e-17, -3.26673292e-16,
       -3.28148358e-16,  1.00000000e+00, -1.14589077e-16,  1.26190986e-16,
       -1.39878289e-16, -2.40132222e-16,  2.19465236e-16,  1.11875128e-16,
        1.00000000e+00,  1.00000000e+00, -1.84971304e-16,  1.00000000e+00,
        1.00000000e+00,  9.43720209e-18,  1.00000000e+00,  1.08792298e-16,
        2.51820815e-16, -1.85991984e-16,  1.00000000e+00, -2.08099896e-16,
       -2.84022823e-16,  1.47859282e-16,  1.00000000e+00, -4.08896945e-16,
       -3.09623486e-16,  2.15332702e-16, -3.88929389e-16, -3.38432674e-16,
        1.00000000e+00,  2.31972486e-16,  1.00000000e+00,  1.00000000e+00,
       -1.59847923e-16, -2.46991952e-16,  2.28467349e-16, -1.70163824e-16,
        2.01615413e-16, -1.86268757e-16,  1.00000000e+00, -3.17645868e-16,
       -1.11212233e-16, -2.33503196e-16,  2.57710268e-17,  1.72061163e-16,
        1.00000000e+00, -3.10150655e-16,  1.36871693e-16, -1.47943970e-16,
       -3.14183496e-16,  1.00000000e+00, -1.11801753e-16, -2.69284319e-17,
       -3.89326527e-16,  2.66592483e-16,  2.20710753e-16,  1.84641498e-16,
       -3.70328710e-16,  2.16247307e-16, -2.44581682e-16,  1.00000000e+00,
        1.21236254e-16,  1.00000000e+00, -3.36886175e-16, -2.80531692e-16,
        1.00000000e+00, -1.81202156e-16,  1.00000000e+00,  4.92689417e-17,
       -1.44015711e-16, -2.44209426e-16, -2.58952585e-16, -3.44434123e-16,
       -3.39328561e-16,  7.05054573e-17,  1.92520039e-16,  5.94046675e-17,
        1.97910889e-16, -2.21298156e-16,  2.64854169e-16,  1.42200982e-17,
        1.00000000e+00,  2.47171009e-16,  1.98738028e-16,  1.00000000e+00,
       -2.97627392e-16,  1.00000000e+00,  1.00000000e+00, -4.04051841e-16,
        2.51923262e-16, -1.73114967e-16, -2.50055232e-16, -1.57640720e-16,
        2.27721788e-17,  2.12627317e-16,  1.00000000e+00,  1.00000000e+00,
        1.11342945e-16,  1.00000000e+00, -2.77233462e-16,  2.95232029e-17,
       -1.09759153e-16,  1.00000000e+00,  3.84327992e-19,  6.65971934e-17,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00, -3.39201888e-16,
       -2.75540666e-16,  1.00000000e+00,  1.00000000e+00, -1.31613042e-16,
       -1.43881021e-16,  2.77302801e-16, -1.97961576e-16,  3.88707676e-17,
        2.77174509e-16, -3.99251491e-16, -3.85165928e-16,  1.29961521e-16,
        1.00000000e+00,  1.00000000e+00, -3.50474657e-16, -3.29226143e-16,
       -2.54202820e-16, -2.51413845e-16, -1.83193498e-16,  4.66622708e-17,
        1.00000000e+00,  1.00000000e+00,  5.51911742e-17,  1.00000000e+00,
        1.92027190e-16,  1.00000000e+00,  4.49382119e-17, -2.40313266e-16,
        1.00000000e+00,  1.00000000e+00, -2.85619764e-16, -2.06860022e-18,
       -2.88893806e-16, -1.30741486e-16, -2.46007745e-16,  2.40628222e-16,
        1.25791735e-16,  1.45516536e-16, -2.90209601e-16,  1.76397972e-16,
        1.30702602e-16,  1.00000000e+00,  2.23878704e-16, -1.21789460e-16,
        2.29528316e-17, -2.97477007e-16,  2.39934120e-16,  1.00000000e+00,
        1.00000000e+00,  2.00027908e-16, -3.34241378e-16,  1.00000000e+00,
        1.41639144e-16, -3.91864058e-16,  4.74688111e-17, -1.95998956e-16,
       -2.00950241e-16,  1.95036437e-16,  2.09219205e-16,  1.00000000e+00,
        1.06863768e-16,  1.05668800e-16, -1.12305606e-16,  5.50939162e-17,
       -3.78617543e-16, -2.44173863e-16,  4.52710080e-17,  1.76699060e-16,
        2.79166348e-16, -3.73133487e-16,  3.45045967e-17,  1.00000000e+00,
       -1.15663398e-16,  1.95747462e-16,  1.00000000e+00, -1.64711211e-16,
        2.40463423e-16,  1.00000000e+00,  1.30391612e-16, -3.00695310e-16,
        1.00000000e+00,  6.97219719e-17,  1.57494320e-16, -1.22409090e-16])

In [17]:
#untuk menghitung R2 Score
r2_mlr = r2_score(ym_test, ym_pred)
print(r2_mlr)

1.0